server:
  port: 8089
  servlet:
    context-path: /demo
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ruoyi.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  #用于mybatis在控制台打印sql日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: ERROR
    org.springframework: ERROR
    org.mybatis: ERROR
    com.ruoyi.dts.wx: DEBUG
    com.ruoyi.dts: INFO
spring:
  profiles:
    active: dev

pagehelper:
  helperDialect:  mysql
  reasonable: true
  supportMethodsArguments:  true
  params: count=countSql